CREATE VIEW SCHOOLS(SCHOOL_NAME, SAFETY_RATING, FAMILY_RATING, 
					  ENVIRONMENT_RATING, INSTRUCTION_RATING, LEADERS_RATING,
					  TEACHERS_RATING)
	AS SELECT NAME_OF_SCHOOL, SAFETY_ICON, FAMILY_INVOLVEMENT_ICON,
			ENVIRONMENT_ICON, INSTRUCTION_ICON, LEADERS_ICON, 
			TEACHERS_ICON
	FROM CHICAGO_PUBLIC_SCHOOLS;
	
SELECT * FROM SCHOOLS;

SELECT SCHOOL_NAME, LEADERS_RATING FROM SCHOOLS;