--#SET TERMINATOR @
CREATE PROCEDURE UPDATE_LEADERS_SCORE (IN IN_SCHOOL_ID INTEGER,IN IN_LEADER_SCORE INTEGER)
LANGUAGE SQL 
BEGIN 
	UPDATE CHICAGO_PUBLIC_SCHOOLS 
	SET "LEADERS_SCORE"=IN_LEADER_SCORE 
	WHERE "SCHOOL_ID"=IN_SCHOOL_ID;
	
IF in_Leader_Score > 0 AND in_Leader_Score < 20 THEN
	UPDATE CHICAGO_PUBLIC_SCHOOLS 
	SET "LEADERS_ICON"='VERY WEAK';

ELSEIF in_Leader_Score < 40 THEN
	UPDATE CHICAGO_PUBLIC_SCHOOLS 
	SET "LEADERS_ICON"='WEAK';

ELSEIF in_Leader_Score < 60 THEN
	UPDATE CHICAGO_PUBLIC_SCHOOLS 
	SET "LEADERS_ICON"='AVERAGE';

ELSEIF in_Leader_Score < 80 THEN
	UPDATE CHICAGO_PUBLIC_SCHOOLS 
	SET "LEADERS_ICON"='STRONG';

ELSEIF in_Leader_Score < 100 THEN
	UPDATE CHICAGO_PUBLIC_SCHOOLS 
	SET "LEADERS_ICON"='VERY STRONG';
	
ELSE 
	ROLLBACK WORK ;
	
END IF;

COMMIT WORK ;
END@